ALTER TABLE public.events
ADD COLUMN IF NOT EXISTS end_date DATE,
ADD COLUMN IF NOT EXISTS event_time TEXT;

ALTER TABLE public.events
ALTER COLUMN start_date DROP NOT NULL,
ALTER COLUMN end_date DROP NOT NULL,
ALTER COLUMN event_time DROP NOT NULL;
